#!/bin/bash
set -u -e -E -C -o pipefail

NR_X=30
NR_Y=$NR_X
COLORS=$(seq 2 6)

OUTDIR=out
mkdir -p $OUTDIR

shopt -s nullglob
FILES=${@:-$(eval *.JPG)}

if [[ -z $FILES ]]; then
    echo "no files given"
    exit 1
fi 

for thisFILE in $FILES; do
    thisBASEFILE=$(basename $thisFILE .JPG)
    rm -f $OUTDIR/$thisBASEFILE-*.JPG
    echo -n "$thisBASEFILE:"

    thisORIGFILE=$OUTDIR/$thisBASEFILE-orig.JPG
    convert -type Grayscale $thisFILE $thisORIGFILE
    echo -n " orig"

    for thisCOLORS in $COLORS; do
        echo -n " $thisCOLORS"
        thisOUTFILE=$thisBASEFILE-$thisCOLORS.JPG
        convert \
            -scale ${NR_X}x${NR_Y} \
            -dither None \
            -colors $thisCOLORS \
            -equalize \
            -scale 1000% \
            $thisORIGFILE \
            $OUTDIR/$thisOUTFILE &
    done
    wait
    echo
done
util/indexing.sh
